# Generated by Django 4.0.10 on 2023-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_task_options_alter_task_priority_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='todos.task'),
        ),
    ]
